# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktrai < Formula
  desc "AI agent context scaffolding for software repositories. Installs a .agent/ layout with AGENTS.md, ctags-driven symbol index, and Cursor + Claude rule symlinks.
"
  homepage "https://github.com/kennytrytek/ktrai"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kennytrytek/ktrai/releases/download/v0.6.2/ktrai_0.6.2_darwin_amd64.tar.gz"
      sha256 "717e7afa4b1e76a838ae997ee92d4f561ea1e9794f1a77351cb9c6804e615f1d"

      define_method(:install) do
        bin.install "ktrai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kennytrytek/ktrai/releases/download/v0.6.2/ktrai_0.6.2_darwin_arm64.tar.gz"
      sha256 "abade3de46c3ab4eb1b6a52f79de8a4e92fbebefef9c103cd1867b600f028bf4"

      define_method(:install) do
        bin.install "ktrai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennytrytek/ktrai/releases/download/v0.6.2/ktrai_0.6.2_linux_amd64.tar.gz"
      sha256 "c4ee07070937b0106c694a4ee3ad1c1c9e573612ab5edcd02ab8cbad732c7a36"
      define_method(:install) do
        bin.install "ktrai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kennytrytek/ktrai/releases/download/v0.6.2/ktrai_0.6.2_linux_arm64.tar.gz"
      sha256 "a54e6d5d40a54d29f6eeb30dcdf5d9579119d234e0dd97c1961dbea90c36f562"
      define_method(:install) do
        bin.install "ktrai"
      end
    end
  end

  test do
    system "#{bin}/ktrai", "--version"
  end
end
